---
- name: Install Docker # Выполнять всё будем на хосте с именем Prod с правами суперпользователя (root), также отключаем автоматический сбор фактов
  hosts: localhost
  gather_facts: no
  become: true
  vars:
    home: /home/mikhailomk/final_git # Папка, в которую загрузим репозиторий
    docker_repo: https://download.docker.com/linux/ubuntu
    docker_gpg_key: https://download.docker.com/linux/ubuntu/gpg
    github_repo: https://github.com/MikhailoMK/Cometa_Final.git

  tasks:
    - name: Install required system packages # Устанавливаем все необходимые зависимости
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - python3-docker
        state: latest

    - name: Add Docker GPG apt Key # Добавляем GPG ключ, чтобы система доверяла пакетам загружаемым из докера
      apt_key:
        url: "{{ docker_gpg_key }}"
        state: present

    - name: Add Docker Repository # Добавляем репозиторий в систему
      apt_repository:
        repo: "deb {{ docker_repo }} focal stable"
        state: present

    - name: Update apt and install docker-ce # Пакеты для работы с докером
      apt:
        name: docker-ce
        state: latest

    - name: Git checkout # Загрузка самого репозитория
      ansible.builtin.git:
        repo: "{{ github_repo }}"
        dest: "{{ home }}"

    - name: Tear down existing services # Запуск файла docker-compose.yml
      community.docker.docker_compose_v2:
        project_src: "{{ home }}/DevOps"
